### ISSUE TITLE
Staff Chat

### ISSUE THREAD

**Issue by RavaPollo** [Qballl/StaffPlus#10]
Hey, so my staff (non opped ) can do /sc and it shows the usage, but /sc (message) does nothing for them, it shows in console the message but the staff can't view the message/view other people's messages. I'm using latest build, 1.12 server. I added permissions.staff-chat to the rank, but still doesn't work

**Comment by Qballl** [comment]
I will look into this

**Comment by RavaPollo** [comment]
So have you fixed it yet?

**Comment by Qballl** [comment]
Tbh not looked at it yet

**Comment by Qballl** [comment]
I know it's been a while but I will look into this tomorrow

**Comment by Qballl** [comment]
I think this is a permission error but Im not sure. Im gonna see about testing it today.

**Comment by Qballl** [comment]
I tested it today and had no problems must be an error on your end. Double check your permissions, please.

**Comment by Qballl** [comment]
Hey are you still having issues or can I close this?
