### ISSUE TITLE
Feature Request - Random Teleport

### ISSUE THREAD

**Issue by SamKingDev** [Qballl/StaffPlus#101]
It would be amazing if you could add the ability for the plugin to tell you who you've been teleported to with some kind of placeholder.

Thanks

**Comment by AigleDev** [comment]
You're request is to add PAPI support to the message when you got random teleported ?

**Comment by Smadger1** [comment]
No sorry, when you get randomly teleported it would be super helpful for it to say in chat you've been teleported to player. Where player is the player you've been teleported to username.

On Mon, 2 Sep 2019, 22:59 AigleDev, <notifications@github.com<mailto:notifications@github.com>> wrote:

You're request is to add PAPI support to the message when you got random teleported ?

**Comment by Qballl** [comment]
Alright shouldn't be hard to add

**Comment by SamKingDev** [comment]
@Qballl I hate to be a pain but is there any update with this?

Could we just re-open that pull request and merge?
