### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by sandor111** [Qballl/StaffPlus#102]
Spigot ver 1.13
https://pastebin.com/chgeZp4D

**Comment by Azoraqua** [comment]
Alright, thanks for notifying us. We'll take a look at it.

**Comment by AigleDev** [comment]
`Excessive velocity set detected: tried to set velocity of entity SteffJonez id #712340 to (2.09746196116341,-0.274793204765056,4.530468189501775).`
change the velocity in config to a lower number and should work ^^

**Comment by Azoraqua** [comment]
I assume the issue is fixed and therefore I'll close this issue.
