### ISSUE TITLE
Strange Error

### ISSUE THREAD

**Issue by giuliotoplad** [Qballl/StaffPlus#103]
https://paste.ubuntu.com/p/72sHjBdd9g/
Minecraft 1.12.2 Paper
Staff+ v3.2.9.3

**Comment by Azoraqua** [comment]
Seems like the auto-updating part isn't implemented correctly. 
Thanks for notifying us.

**Comment by giuliotoplad** [comment]
Ok, then I'll wait for this error to be solved, thanks for the quick reply.
