### ISSUE TITLE
Staffchat not private

### ISSUE THREAD

**Issue by sandor111** [Qballl/StaffPlus#104]
When enabling staffchat the message is send in both the public chat and staff chat.

![Screenshot_725](https://user-images.githubusercontent.com/17690323/63933769-28176500-ca5a-11e9-99d2-ebb44370db64.png)

**Comment by Azoraqua** [comment]
Alright, thanks for notifying about this potential bug. 
@Qballl Mark as 'bug' please.

**Comment by Qballl** [comment]
Check this with a non staff account

**Comment by sandor111** [comment]
> Check this with a non staff account

A non staff account is also able to see the message, I am using chatcontrol as chat formatting plugin

**Comment by Azoraqua** [comment]
It might be that ChatControl interferes with StaffPlus. Not sure though.
