### ISSUE TITLE
Invalid inventory size; expected 27 or less

### ISSUE THREAD

**Issue by sandor111** [Qballl/StaffPlus#107]
Paperspigot 1.13.2
StaffPlus version 3.2.9.3
https://pastebin.com/LeFTkJuW

**Comment by Azoraqua** [comment]
Thanks for mentioning it. We'll take care of it.

**Comment by sandor111** [comment]
Could this be looked into?

**Comment by Azoraqua** [comment]
We'll look into it, eventually. at the moment it's not our main priority due to other things being more important.
