### ISSUE TITLE
/staff isn't working, all other commands are

### ISSUE THREAD

**Issue by Scuffi** [Qballl/StaffPlus#11]
Hello, StaffPlus is loading fine and no errors on startup:
'[14:23:46] [Server thread/INFO]: [Staff+] Version protocol set to 'v1_8_R3'.
[14:23:46] [Server thread/INFO]: [Staff+] Staff+ has been enabled! Initialization took 173ms.
[14:23:46] [Server thread/INFO]: [Staff+] Plugin created by Shortninja.'

All other staff+ commands I've tried have worked. Except /staff which doesn't spit out any output to chat or console, it doesn't do anything. 

Thanks

**Comment by Qballl** [comment]
Ill look into this later on tonight

**Comment by Qballl** [comment]
Ooo

**Comment by Scuffi** [comment]
It is

**Comment by Qballl** [comment]
hmm may be a 1.8 issue I'll have to test that

**Comment by Scuffi** [comment]
Updates?

**Comment by Qballl** [comment]
None yet been busy with family stuff

**Comment by Qballl** [comment]
I know it's been a while but I will look into this tomorrow

**Comment by Qballl** [comment]
Not happening for me on 1.8 either are you sure you have permission although testing this made me find a new bug

**Comment by Scuffi** [comment]
Sorry I took so long to respond, I am op so I will have all permissions

**Comment by Qballl** [comment]
Hmm that is weird because Im op too and it works

**Comment by Qballl** [comment]
I have no idea why /staff isn't working for you I have. Can you provide some more information?

**Comment by Scuffi** [comment]
I'll reinstall it and see.

**Comment by Scuffi** [comment]
I've found a new error now, whenever I upload it, I'm stuck on the Logging in... screen until I timeout. Works perfectly fine without the plugin.

**Comment by Qballl** [comment]
Hmm that is no good I will test this myself I think I've experienced this problem when reloading the plugin with plugman

**Comment by Qballl** [comment]
Are you still having issues

**Comment by Qballl** [comment]
Closing this
