### ISSUE TITLE
Kicked when using staff mode

### ISSUE THREAD

**Issue by topthat177** [Qballl/StaffPlus#111]
After about 10-20 seconds of enabling staff mode, I get booted from my server. This is what comes up in console. No obvious error, not sure why its printing unknown command messages after I use /staff in game.

Console: https://pastebin.com/huEcS3SP
Version: 3.2.9.3
Server Version: Paper 1.14.4

Kick Message:
![Capture](https://user-images.githubusercontent.com/29544476/65738215-73d63080-e124-11e9-80dc-fabc78ae9c2a.JPG)

**Comment by Monsterek** [comment]
I have same problem

**Comment by Azoraqua** [comment]
That's a known issue. Use the newest release: https://github.com/Qballl/StaffPlus/releases/tag/3.2.9.
