### ISSUE TITLE
Launcher tool gives error message even when successfully used

### ISSUE THREAD

**Issue by Jadiction** [Qballl/StaffPlus#114]
When using the launcher tool regardless of direction or if you're going through something, it still gives the message "Nothing to pass through (or too far)".
![Example](https://user-images.githubusercontent.com/8557785/65838816-b63a7180-e2cc-11e9-84f8-943b4897c09f.png)

**Comment by Azoraqua** [comment]
Do you have WorldEdit installed by accident? Because WorldEdit has a feature to teleport players when clicking with a compass.

**Comment by Jadiction** [comment]
Yeah, WorldEdit is installed; ideally, you guys could hook and prevent the message.

**Comment by Qballl** [comment]
I will see what I can do
