### ISSUE TITLE
Hiding IP from the Examine tool "disables" it.

### ISSUE THREAD

**Issue by Jadiction** [Qballl/StaffPlus#115]
When assigning the permission `staff.staffplus.hideip` (or whatever "ipPerm" is set to) to a player and using the examine tool on them, it does nothing.
I'd assume it would just hide the "connection" item or the tooltip for it. Is this intentional? If so, may I suggest doing the above?

**Comment by Qballl** [comment]
Fixed now. Now if a user has that permission it returns 127.0.0.1 which as we all know is localhost. I could change it if enough people request
