### ISSUE TITLE
AutoFill Bug / Feature I'm not aware of :(

### ISSUE THREAD

**Issue by topthat177** [Qballl/StaffPlus#117]
Hi,

I had the issue with being Kicked when using Staff Mode and this was resolved by updating to the latest release. However, now the plugin seems to be preventing the auto tab fill for commands from working properly. By a process of plugin elimination on my test server I have confirmed it is Staff Plus causing the issue.

It works for sub commands ie: when running essentials, typing /fly can be tab completed to /flyspeed. 

However, Staff Plus is preventing playernames being tab completed ie: /fly topthat177 or cycling through other online players by continually pressing tab after entering the command.

Server Version: Paper 1.14.4
Plugin Version: Latest Release --> https://github.com/Qballl/StaffPlus/releases/tag/3.2.9

If this is a feature or supposed to happen, is there a way to revert it back to normal tab completes or off completely in the config?

**Comment by Azoraqua** [comment]
Yes, we are aware of this bug. We'll take care of that as soon as possible.
Thanks for the detailed explanation.

**Comment by Qballl** [comment]
Apparently this is now fixed on the newest dev version closing

**Comment by Qballl** [comment]
Fixed. Non vanished players were not being accounted for now it seems to be working fine
