### ISSUE TITLE
Version Protocol Bug

### ISSUE THREAD

**Issue by giuliotoplad** [Qballl/StaffPlus#118]
Staff+ Version v3.3.0.0
Minecraft Server Version: 1.12.2 Spigot
Bug: https://paste.ubuntu.com/p/Qq5bmqGhDW/
I had already reported this Bug before the Update but apparently it hasn't been solved.
Note that in the last Staff+ Release this Bug is still present.

**Comment by Azoraqua** [comment]
Forgot to remove the placeholder it seems. Well, shouldn't be too important as it's only related to auto-updating.

**Comment by giuliotoplad** [comment]
Ok, but since it's a trivial thing, could you solve it anyway, please?

**Comment by Azoraqua** [comment]
We'll take a look into it. I'll close this issue now.

**Comment by giuliotoplad** [comment]
OK thanks.
As soon as a new update is released I will let you know if it has been resolved.
