### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by GabrielHD150** [Qballl/StaffPlus#119]
![image](https://user-images.githubusercontent.com/44451794/68483361-ca4d8900-0211-11ea-93c6-12343f8aa0ca.png)
Plugin performance is fatal to just be a StaffMode plugin

**Comment by Qballl** [comment]
That's the auto saving feature. If you were to open the config you can see you can change the interval it runs at thus decreasing the impact. Also, that process is fairly quick so the actual impact is minimal. Just b/c it shows up red doesn't mean it's bad.
