### ISSUE TITLE
StaffPlus won't enable

### ISSUE THREAD

**Issue by srnyx** [Qballl/StaffPlus#122]
I have the latest version, but I always get this error:
Using PaperSpigot 1.14.4

`ERROR Error occurred while enabling StaffPlus v3.3.0.0 (Is it up to date?)`

**Comment by Azoraqua** [comment]
Can you give me the output of `/plugins`?

**Comment by GITVenox** [comment]
Yeah, Vault is installed:
[INFO] Plugins (40): BuycraftX, CoreProtect, DiscordSRV, dynmap*, Dynmap-Essentials*, Dynmap-GriefPrevention*, EnjinMinecraftPlugin, Essentials, EssentialsSpawn, GriefPrevention, HolographicDisplays, KillerMoney*, LuckPerms, LuckPerms-GUI, MineTinker-Elevators, Multitool, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, OldCombatMechanics, PacketListenerApi*, PlaceholderAPI, ProtocolLib, RankGrantPlus, SerialKey, Shop, Shopkeepers, Spiderman*, StaffPlus, SuperVanish, TrollBoss, UltimateCatcher, UltimateKits, UltimateStacker, UltimateTimber, Vault, VentureChat, Wild, WorldEdit

Well, PacketListenerAPI also didn't load before it, I don't know if that has something to do with it though. This has happened a lot before as well.

**Comment by Azoraqua** [comment]
PacketListenerAPI is a thing that's needed for StaffPlus.

**Comment by GITVenox** [comment]
I already reported that PacketListenerAPI won't load on their GitHub, so it might be on their side.
If they fix that issue and StaffPlus still doesn't work I'll tell you.

**Comment by Azoraqua** [comment]
That's fine. I'll be stand-by.

**Comment by Qballl** [comment]
Could you share more of the startup of staffplus

**Comment by GITVenox** [comment]
[Everything I could find that had "StaffPlus" in it](https://gist.github.com/GITVenox/c2c74c974e383eb5e8186dfc19c2bb07)

**Comment by GITVenox** [comment]
I'll try reinstalling PacketListenerAPI

**Comment by Qballl** [comment]
Any update?

**Comment by srnyx** [comment]
It's still happening

**Comment by Qballl** [comment]
Can you resupply the error that link isn't working anymore

**Comment by srnyx** [comment]
https://gist.githubusercontent.com/srnyx/c2c74c974e383eb5e8186dfc19c2bb07/raw/e282b7ff961f1d968be3f503e3cd920e70776578/gistfile1.txt

**Comment by Qballl** [comment]
Is this all there is to it?

**Comment by srnyx** [comment]
Currently, yes.
But, I have reason to believe it has something to do with PacketListenerAPI (it says that in the console), I've already sent a report to them, but there is still no update

**Comment by Qballl** [comment]
Any update now with the new versions of Staff+

**Comment by srnyx** [comment]
_I think it's safe to say I can close this now (yes, it's working again)_
