### ISSUE TITLE
XP Removed When Exiting Staff Mode

### ISSUE THREAD

**Issue by Stixil** [Qballl/StaffPlus#128]
Players who collect XP during staff mode lose all levels upon returning to normal mode. This makes it difficult for normal survival players to assist with staff responsibilities in my SMP server.

Thanks!

**Comment by Qballl** [comment]
Will definitely look into that

**Comment by Stixil** [comment]
Thanks!

**Comment by Qballl** [comment]
Alright so I just got around to looking at the code for staffmode and right now I dont see anywhere it touches player xp so Im not sure why this is happening

**Comment by Qballl** [comment]
Well I now save xp to a file and reset it so hopefully, that takes care of this.
