### ISSUE TITLE
Request: enable tracking/reporting offline players

### ISSUE THREAD

**Issue by Stixil** [Qballl/StaffPlus#129]
Hi, we would love to see the ability to access/make notes, reports, etc for offline players. Thanks!

**Comment by katiebosch** [comment]
I would also love to see this! It's a bit of a hassle to have to wait until a player comes on to check their info or issue a warning.

Love this plugin!

**Comment by Qballl** [comment]
I will see what I can do

**Comment by garagepoort** [comment]
I implemented part of this in my own fork of this amazing repo.
https://www.spigotmc.org/resources/staff.83562/
https://github.com/garagepoort/StaffPlusPlus

Offline players can be reported and warned.

Only v1.15 and v1.16 are supporting the offline players for now.
But I will probably implement this in v1.13 & v1.14 as well
