### ISSUE TITLE
Staff+ - Add Features

### ISSUE THREAD

**Issue by DoNotLegit** [Qballl/StaffPlus#13]
Hi,

Please Add Knockback Sword to Verify the AntiKb of the Player (In the Config Please Add "Enchantement : Knockback2")

Please Add in the Config To change the random teleportation command (Default : /tp %randomplayer%) to (/teleport %randomplayer%) It's Example

Thank you

**Comment by Qballl** [comment]
Im working on this now but is there a command for randomly teleport a player already?

**Comment by Qballl** [comment]
Im gonna close this the sword seems unnecessary
