### ISSUE TITLE
Teleporting to another world while in staff mode messes up Inventories

### ISSUE THREAD

**Issue by Jadiction** [Qballl/StaffPlus#133]
* Activate staff mode in world 1
* Teleport to world 2

You'll still be in staff mode but without the hotbar functions, if you /staff again your inventory gets overrode from the other world's inventory (this is definitely not good if you go from a creative world to a survival world)
Additionally, if you go back to world 1, you will have the items from the /staff hotbar but they are no longer functional, they are items. Example:

![](https://image.prntscr.com/image/aDV5VVufRIeoXH0aRRkAaw.png)

I saw an [older post with this similar issue](https://github.com/Qballl/StaffPlus/issues/22) but doesn't appear to be in effect now.

**Comment by Qballl** [comment]
Believe this is fixed now
