### ISSUE TITLE
Lead from staff mode hotbar is duplicatable 

### ISSUE THREAD

**Issue by Jadiction** [Qballl/StaffPlus#134]
* Use /staff
* Use the lead (The follow function at the end of the hotbar) on an animal
* It actually uses it allowing you to get it back, deactivate staff & reactivate and repeat.

**Comment by Qballl** [comment]
I believe this is the underlying issue as #127 so closing this

**Comment by Jadiction** [comment]
I don't think it is, but I guess it's possible.
