### ISSUE TITLE
Don't work on KCauldron

### ISSUE THREAD

**Issue by YorenAijin** [Qballl/StaffPlus#138]
i put on my 1.7.10 cauldron and it dosnt work, plz help me

**Comment by Qballl** [comment]
I'm gonna need more information

**Comment by YorenAijin** [comment]
I have a server who work on Cauldron, its in 1.7.10 version, when i start it with the plugin, the plugin is not detected by the server
my discord if you can help me and u want some more information : Yoren_Aijin#9321

**Comment by Qballl** [comment]
https://discord.gg/vAKMuD And Im gonna need a startup log

**Comment by Neewen** [comment]
Hello, so the problem is solved ?

**Comment by Azoraqua** [comment]
I am going to close the issue because StaffPlus is not supposed to be supported on Cauldron. If it will be supported eventually one of us will let you know.
