### ISSUE TITLE
Vanish & custom modules executes twice when you right-click on a block

### ISSUE THREAD

**Issue by Jadiction** [Qballl/StaffPlus#139]
For a while, I didn't know why vanish sometimes repeated on 1 right-click, but I've recently learned that it happens when you right-click the vanish module on a block. If I were to right-click the air, it executes once, but if I right-click on a block, it executes twice. The same goes for custom modules as well.

**Comment by Jadiction** [comment]
This is related to https://github.com/Qballl/StaffPlus/issues/127 but this has the cause of the issue.

**Comment by Azoraqua** [comment]
The reason is that Bukkit's PlayerInteractEvent works that way. It's a little.. buggy if you don't know how to work with it.
I believe it's because it registers it as two sequential clicks instead of one. 

I am not sure if it's already fixed though.
