### ISSUE TITLE
Default configuration English character bug In staff list GUI

### ISSUE THREAD

**Issue by Neewen** [Qballl/StaffPlus#143]
Here is the character bug :
![image](https://user-images.githubusercontent.com/62424178/80411325-4fb21c00-88cc-11ea-9ca8-214f6400939b.png)

Versions:
![image](https://user-images.githubusercontent.com/62424178/80411426-7c663380-88cc-11ea-8067-2409c05e2bb5.png)
![image](https://user-images.githubusercontent.com/62424178/80411448-8425d800-88cc-11ea-85cc-777a6d552729.png)
![image](https://user-images.githubusercontent.com/62424178/80411478-8e47d680-88cc-11ea-93ad-f2cd0f69b376.png)

**Comment by Azoraqua** [comment]
Seems to be an encoding issue. Should be fixed in newer versions.
