### ISSUE TITLE
Information request for StaffPlus Plugin

### ISSUE THREAD

**Issue by DoNotLegit** [Qballl/StaffPlus#15]
Hi,

I would like to know if your plugin was open source to improve it on my side because there is a lot of bug in the current version
For example , The chat slow does not work
And it lacks a lot of basic features on StaffPlus

I thank you in advance

**Comment by Qballl** [comment]
It is, you can make all the changes you want. I would love though if after making your changes you create a pull request it would help out everyone using the plugin. The pull request isn't needed if you make changes it's just something I would love to see much how spigot would love to see pull requests with changes people make.

**Comment by Qballl** [comment]
Im gonna close this and if you did make changes please consider doing a pull request
