### ISSUE TITLE
Error on load 

### ISSUE THREAD

**Issue by Shiade** [Qballl/StaffPlus#157]
When the plugin is being enabled an error appears in the console and some functions such as staffchat do not work

And another thing, I don't know if it's the same error but when the plugin is on my server it doesn't let anyone in, it just takes them out of the server, and when I remove the plugin again it lets everyone play normally

https://pastebin.com/7JwaZuDs

**Comment by Azoraqua** [comment]
Is a known issue regarding PacketListenerAPI. You may want to report the issue to Haylee/InventiveTalent at https://github.com/InventivetalentDev/PacketListenerAPI.
