### ISSUE TITLE
Config.yml not updated in game, /staffplus reload same

### ISSUE THREAD

**Issue by xXFlaneXxPro** [Qballl/StaffPlus#160]
Hello!

I have same issues, when i edit config.yml and i save the folder is not saving in the game and is running the old file. Restart not working and /staffplus reload work just for lang_en , when i edit in lang_en work after a restart or reload, idk exaclty. What can i do? Console is clear and is not saying something about this.

**Comment by Azoraqua** [comment]
Shutdown the server, edit the config and start it again generally provides the best results.
Do not use /reload or /staffplus reload because both might cause issues.

**Comment by xXFlaneXxPro** [comment]
Done, i found another solution... the config.yml folder was a old version and i paste to the new version. He don t was different is just have the #... write but now is done, a little question... how can i acces the counter-list without the staff mode, for see the staff online like in staff mode, no /personnel command and how i set to can t teleport to this person using that command

**Comment by JohnnyKnowing** [comment]
I am also having this trouble.  OP, how did you solve this problem?  When I reset my server the config.yml resets to default and my edited config file get its name changed to backup-#6204.yml
