### ISSUE TITLE
Staff + Adding New features

### ISSUE THREAD

**Issue by AlonsoAliaga** [Qballl/StaffPlus#17]
Hi i wonder if you could add something to the plugins.
**1)** Add cooldown to custom items in the hotbar. Something like:
  custom-modules:
    name:
       enable: true
       type: COMMAND_CONSOLE
       [...]
       cooldown: 30//in seconds
so the command cannot be spammed.
**2)** Mysql, will be added to sync notes or alerts like:
- AlonsoAliaga has mined 1 diamond (12) in Survival
the name of the server.
I hope those features were added soon 👍

**Comment by Qballl** [comment]
1 possibly 2 I need to learn mysql firat

**Comment by AlonsoAliaga** [comment]
1st would be nice. 2nd can wait a long time jet.
I just realized there was an option to join in staffmode, i was going to ask for a permission to be added.
Thanks for replying.

**Comment by Qballl** [comment]
I plan on getting to this how soon idk school is keeping me busy

**Comment by Qballl** [comment]
Im working on MySQL now and the first thing will go into the next update MySQL is taking priority

**Comment by Qballl** [comment]
Closing this for now as I don't see a need for the cooldown thing
