### ISSUE TITLE
Disabled random teleportation in specific world

### ISSUE THREAD

**Issue by SnaiilGaming** [Qballl/StaffPlus#171]
Hi

My request is on the title.
Is it possible to add in the configuration the possibility to disable the random teleportation in specific world like :
disabled_world: "world_the_end, world_nether" ...

Thx

**Comment by obliviator123** [comment]
Just don't random tp in certain worlds......

**Comment by Qballl** [comment]
There is literally no need for that as to disable wild in a world you simply don't add it to the regions section
