### ISSUE TITLE
Translating Problem

### ISSUE THREAD

**Issue by ziyaakay** [Qballl/StaffPlus#184]
I translated Staff+ to Turkish. And when i tried to restart my server, it closed itself giving errors that i dont know what it means. Can you take a look at it. I really want to use StaffPlus in my server.

[Here](https://easyupload.io/d18cdr) is my language file. 

And [here](https://pastebin.com/P2UH1Xah) is the error i take.

Please give me some information when you fix this.

**Comment by Qballl** [comment]
Can you provide the lang as a pastebin too?

**Comment by ziyaakay** [comment]
> Can you provide the lang as a pastebin too?

Ok, [Click Me!](https://pastebin.com/cQ2NciA8)

**Comment by BalinGrant** [comment]
You missed closing a string on line 180, a fixed version can be found [Here](https://paste.bgbuddyboy.tech/kzbRONAmlN.yaml)

**Comment by ziyaakay** [comment]
I have [this](https://pastebin.com/aJh7jnx8) error now :(

**Comment by Azoraqua** [comment]
When using special characters, escape them using `\`

**Comment by ziyaakay** [comment]
I only use characters from Turkey. Which is "ı,İ,Ü,Ö,Ç,Ş,Ğ". And this characters should not be a problem in UTF-8.

> When using special characters, escape them using `\`

**Comment by Azoraqua** [comment]
Depends on a few things, which encoding the language files are saved in as well as which encoding the java runtime is started with.
By default, on Windows, it's windows-1252 (Also known as CP-1252). In which case it'll either result in an error if it cannot parse it or it causes those square-like characters.

**Comment by ziyaakay** [comment]
The problem is, i cant find the character that error says. Its  with a ? in the middle but it just doesnt exist. I tried replacing all s with what they should be and it keeps saying "Unacceptable code point '' in position 457"

**Comment by ziyaakay** [comment]
> Depends on a few things, which encoding the language files are saved in as well as which encoding the java runtime is started with.
> By default, on Windows, it's windows-1252 (Also known as CP-1252). In which case it'll either result in an error if it cannot parse it or it causes those square-like characters.

I dont get any error with other plugins that i translated before. Nothing changed but plugin.

**Comment by Azoraqua** [comment]
Noted. You can see the progress in another issue #185.
