### ISSUE TITLE
StaffPlusAPI doesn't build

### ISSUE THREAD

**Issue by whtisusername** [Qballl/StaffPlus#189]
[INFO] Reactor Summary for Staff+ 3.3.4.0:
[INFO] 
[INFO] Staff+ ............................................. SUCCESS [  0.337 s]
[INFO] StaffPlusAPI ....................................... FAILURE [02:06 min]
[INFO] v1_7_R1 ............................................ SKIPPED
[INFO] v1_7_R2 ............................................ SKIPPED
[INFO] v1_7_R3 ............................................ SKIPPED
[INFO] v1_7_R4 ............................................ SKIPPED
[INFO] v1_8_R1 ............................................ SKIPPED
[INFO] v1_8_R2 ............................................ SKIPPED
[INFO] v1_8_R3 ............................................ SKIPPED
[INFO] v1_9_R1 ............................................ SKIPPED
[INFO] v1_9_R2 ............................................ SKIPPED
[INFO] v1_10_R1 ........................................... SKIPPED
[INFO] v1_11_R1 ........................................... SKIPPED
[INFO] v1_12_R1 ........................................... SKIPPED
[INFO] v1_13_R1 ........................................... SKIPPED
[INFO] v1_13_R2 ........................................... SKIPPED
[INFO] v1_14_R1 ........................................... SKIPPED
[INFO] v1_15_R1 ........................................... SKIPPED
[INFO] v1_16_R1 ........................................... SKIPPED
[INFO] v1_16_R2 ........................................... SKIPPED
[INFO] v1_16_R4 ........................................... SKIPPED
[INFO] v1_14_R2 ........................................... SKIPPED
[INFO] v1_16_R3 ........................................... SKIPPED
[INFO] StaffPlus-Core ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:07 min
[INFO] Finished at: 2021-04-19T09:29:13+04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project StaffPlusAPI: Could not resolve dependencies for project net.shortninja.staffplus:StaffPlusAPI:jar:3.3.4.0: Failed to collect dependencies at org.bukkit:bukkit:jar:1.16.2-R0.1-SNAPSHOT: Failed to read artifact descriptor for org.bukkit:bukkit:jar:1.16.2-R0.1-SNAPSHOT: Could not transfer artifact org.bukkit:bukkit:pom:1.16.2-R0.1-SNAPSHOT from/to Qballs-repo (https://repo.qballl.net): Transfer failed for https://repo.qballl.net/org/bukkit/bukkit/1.16.2-R0.1-SNAPSHOT/bukkit-1.16.2-R0.1-SNAPSHOT.pom 522 Origin Connection Time-out -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :StaffPlusAPI

**Comment by Qballl** [comment]
It builds just fine. You just have to install all versions from 1
7 to 1
1.16.x
