### ISSUE TITLE
StaffPlus Disabling Error Log

### ISSUE THREAD

**Issue by Adaptz** [Qballl/StaffPlus#198]
![](https://i.imgur.com/TPc4Zva.png)
![](https://i.imgur.com/9GcNN68.png)

I get these errors when running my server and it doesn't run what can I do to fix this?

**Comment by Qballl** [comment]
You on the wrong version of SP that is the last one shortninja put out this is mine https://www.spigotmc.org/resources/staff-the-ultimate-moderation-plugin-1-7-1-17.41500/

**Comment by Adaptz** [comment]
Yeah I just realized that, was coming to close this request sorry bout that
