### ISSUE TITLE
[Question] Does the plugin support version 1.18(.2)?

### ISSUE THREAD

**Issue by Pancakes-Studio** [Qballl/StaffPlus#207]
Hello, as it is written in the title, my question is that the plugin supports the version 1.18 including the .2? On the page of Spigot it is written that it supports 1.17 in the most recent version.
Thank you for your understanding.

**Comment by BalinGrant** [comment]
Yes the plugin works on 1.18 versions.
Though you should always [try it and see](HTTP://tryitands.ee)

**Comment by Pancakes-Studio** [comment]
Ok thanks but just now I tried Staff++, which is also a rework of the original (which indicated 1.18 compatibility) and it is perfect for me. Here is Staff++ just in case: [https://www.spigotmc.org/resources/staff.83562/](url)
Thank you for your answer, goodbye and good evening!
