### ISSUE TITLE
Staff+ Feature Request - GUI

### ISSUE THREAD

**Issue by JoshHeng** [Qballl/StaffPlus#21]
Hi,
Would it be possible to have a GUI to make it easier for staff to ban players?
Thanks for all the work

**Comment by Qballl** [comment]
Like would it have predetermined times or would you want it to have configurable times? Also, would the command for this be /ban %player%? But, to answer your question the answer is yes now please provide more info.

**Comment by JoshHeng** [comment]
You would previously set the times/name/item type in config and then when someone did /ban %player%, /punish %player% or right clicked a player with a certain item it would open a GUI.
This would have different items corresponding to the type of punishment (e.g. KillAura, XRay, Griefing, Abuse) and these would automatically execute the /ban, /tempban, /mute, /kick and /warn commands when clicked with a predetermined message and time  

I'm not sure if it's possible but it would be very helpful!

Thanks

**Comment by Qballl** [comment]
It shouldn't be too hard to do (knock on wood) I will see if I can get at least part of this up and going.

**Comment by Qballl** [comment]
Alright I finally have the time to work on this and once I'm done with MySQL I will try to add this

**Comment by ScienceisAmazing** [comment]
How is this feature coming along? I think it would also be cool.

**Comment by Qballl** [comment]
Havent had much time to work on it

**Comment by Azoraqua** [comment]
Will look into it. :)

**Comment by Qballl** [comment]
Alright I have done some thinking and even at its base level it is gonna be a hard system to implement and I'm not sure if it would be worth it as Staff+ is more of a management plugin then a punishment plugin that being said I will give it some time before I make a final decision.

**Comment by Azoraqua** [comment]
After a year, I am going to assume the original opinion is still valid and therefore I am going to close this.
