### ISSUE TITLE
Staff mode with Multiverse Inventories

### ISSUE THREAD

**Issue by JoshHeng** [Qballl/StaffPlus#22]
Sorry to bother you again but when I use /staff in one world and then teleport to another, doing /staff again to turn staff mode off messes up my inventory by giving me the inventory from the previous world.
Is there any way to automatically switch off staff mode when a user disconnects or joins another world, or prevent a user from joining another world in staff mode?
I am using Multiverse and Multiverse Inventories

Thanks!

**Comment by Qballl** [comment]
Ill look at the bukkit api I think there might be a way

**Comment by Qballl** [comment]
The plugin will now take a player out of staffmode on a world change

**Comment by Qballl** [comment]
Do you want me to link you to a build with this fix

**Comment by JoshHeng** [comment]
Yes please

Thanks,
Joshua Heng

**Comment by Qballl** [comment]
https://www.dropbox.com/s/rxjxyhj6j4ori8z/Staff%2B.jar?dl=0

**Comment by JoshHeng** [comment]
Thanks
