### ISSUE TITLE
Aplication

### ISSUE THREAD

**Issue by ProEfeKubic** [Qballl/StaffPlus#23]
Can you add that when you activate the vanish you see yourself, but the users do not?

**Comment by Qballl** [comment]
I dont think I can due to how the vanishing works

**Comment by ProEfeKubic** [comment]
Isn't there some way to do it?

**Comment by Qballl** [comment]
Probably not without messing with NMS even then I can't guarantee but why do you want to see yourself?

**Comment by ProEfeKubic** [comment]
Because I like and why I find useful, for example, see what block these and things like that

**Comment by Qballl** [comment]
I will think about it but I would have to stop the player packet to other players much how disguise plugins send mob packets to other players

**Comment by ProEfeKubic** [comment]
OK.

**Comment by ProEfeKubic** [comment]
Can you do it?

**Comment by Qballl** [comment]
idk there is no documentation for NMS as far as Iknow

**Comment by Qballl** [comment]
I'm gonna see about getting this in now I just finished with school so I'll have some time now

**Comment by Qballl** [comment]
Alright, I've found no way to do this without packets so Im contemplating adding it. I may make a poll and see what other users want

**Comment by Qballl** [comment]
I've got actually got this working now no players see you but you see yourself
