### ISSUE TITLE
Config Error

### ISSUE THREAD

**Issue by pozzzzy** [Qballl/StaffPlus#24]
I had configured the plugin through the config.yml file and loaded it into my server, but the plugin is still using the default config after countless restarts.

Here is my edited config.yml: https://pastebin.com/FcruXv6A

Please could someone either tell me what is wrong or fix my errors?
Thankyou.

**Comment by Qballl** [comment]
Did you get this fixed?

**Comment by Qballl** [comment]
And updates. If you dont reply in a day Im gonna close this

**Comment by pozzzzy** [comment]
Got it thanks
