### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by EvilSlime** [Qballl/StaffPlus#26]
You cannot edit the whole message when doing /report.

**Comment by EvilSlime** [comment]
Only the Prefix of the message

**Comment by Qballl** [comment]
What do you mean?

**Comment by EvilSlime** [comment]
http://prntscr.com/j7u88w You cannot edit the blue messages

**Comment by Qballl** [comment]
Is there a need to though?

**Comment by Qballl** [comment]
Ill see about letting you change the blue part it will be a while MySQL is on the top of the pile for rn

**Comment by Qballl** [comment]
I see your point here as the blue tells you the usage and if you change the command it will not match up. I will see about fixing that. I will make it to where you can at least make the commands match not sure about the rest of the message

**Comment by Qballl** [comment]
Hit close by mistake
