### ISSUE TITLE
Add Command when going into Staff Mode

### ISSUE THREAD

**Issue by EvilSlime** [Qballl/StaffPlus#28]
How about a feature that you can add commands if you go in staff mode

**Comment by Qballl** [comment]
I will see but it will be some time my final exams for my first year of college are coming up so I need to focus on that

**Comment by EvilSlime** [comment]
Oh and maybe another feature when you're fixed with your exams how about silent chest opening in vanish or staffmode?

**Comment by Qballl** [comment]
The chest opening may be hard because Im guessing I'll have to play with packets

**Comment by Qballl** [comment]
The chest opening will be considered for the next-next update. The next update will have MySQL and the commands

**Comment by Qballl** [comment]
@EvilSlime would the silent chest allow for editing of the chest?

**Comment by Qballl** [comment]
Silent chest opening is now done and you can already add custom items with commands to staffmode and do commands when entering staffmode so closing this
