### ISSUE TITLE
/tp not working

### ISSUE THREAD

**Issue by Wilobate** [Qballl/StaffPlus#29]
/tp is not working, both players are online, the one commencing the /tp is op, the other is standard player not even staff. but i get told that "Staff+ >> That player is offline". Im not in vanish cause i thought that may have been the case but it is not.

**Comment by Wilobate** [comment]
Plugin is latest release and latest build of spigot

**Comment by Qballl** [comment]
Hmm that is weird because the rtp module is now no longer interfering with tp

**Comment by Wilobate** [comment]
Maybe when you were changing it to not interfer you missed a peice of code. I know its easy to miss stuff when you got a screenfull of code haha

**Comment by Qballl** [comment]
I doubt it can you send your config?

**Comment by Qballl** [comment]
- [ ]

**Comment by Wilobate** [comment]
Ah fair enough, thank you.

**Comment by Qballl** [comment]
Thanks for pointing it out
