### ISSUE TITLE
Error When I report Someone

### ISSUE THREAD

**Issue by Techno3600** [Qballl/StaffPlus#3]
Hello,

Thanks for taking your time to make the plugin compatible with 1.12, but even with the dependency on my server [this error](https://pastebin.com/Bqtg6Ck7) keeps happening.

Thanks
Techno3600

**Comment by Qballl** [comment]
Oh yea I've seen this report before I need to figure out a way to implement the feature or just remove it

**Comment by Techno3600** [comment]
Awesome!

**Comment by Qballl** [comment]
I have a half fix ready to go

**Comment by Qballl** [comment]
Believe to have this fixed

**Comment by Qballl** [comment]
Are you able to test this if I were to send you a fixed version?

**Comment by Techno3600** [comment]
I will test the new version!
Also, there’s a different bug that’s happening with chat silencing.
When I do _/chat toggle disable_ (when the chat is already enabled), it disables the chat, but if I do /chat toggle enable, it also disables it. Do you know why this is?

**Comment by Qballl** [comment]
Here is a version with the first thing hopefully fixed https://www.dropbox.com/s/rxjxyhj6j4ori8z/Staff%2B.jar?dl=0 I will look into this new thing

**Comment by Techno3600** [comment]
I'm trying it!

**Comment by Qballl** [comment]
Can you confirm the original issue is fixed?

**Comment by Techno3600** [comment]
Sorry, I have been very busy, I will try to test this when my hours of homework is finished.

**Comment by Qballl** [comment]
I closed it because it seems the dropbox version fixes alot of the errors.
