### ISSUE TITLE
StaffMode disables when switching worlds

### ISSUE THREAD

**Issue by FlameHeroDev** [Qballl/StaffPlus#30]
Just as the title says, fix it please <3

**Comment by Qballl** [comment]
If you read the updates I said I added that because I got reports that multi-world inventory was causing problems I will add a config option to enable or disable this in the future aka 3 weeks from now right now school is my priority

**Comment by Qballl** [comment]
Alright I'm going add this this tomorrow

**Comment by Qballl** [comment]
Turns out I forgot to do this I'll add it soon and post an update soon

**Comment by Qballl** [comment]
Here is a link https://www.dropbox.com/s/rxjxyhj6j4ori8z/Staff%2B.jar?dl=0  with a version that fixes this it's a config option by default you will still have staff mode disabled upon world change. The option is under the staff mode module in the config. Tell me if it works right

**Comment by Qballl** [comment]
This has been made Im gonna close this for now
