### ISSUE TITLE
Bungee ?

### ISSUE THREAD

**Issue by Damdamdu95** [Qballl/StaffPlus#32]
Can you made Staff + compatible with bungee. I think a MySQL connection will do the trick.

**Comment by Qballl** [comment]
It would yes but, I dont fully know how to do a MySQL storage system yet I'm currently learning how. Could you though reply with what you would like to see be saved through MySQL

**Comment by Damdamdu95** [comment]
I assumed MySQL because PremiumVanish uses MySQL to communicate data and thanks to MySQL we are still in vanish. (Sorry for my bad english, I'm french)

**Comment by Qballl** [comment]
Working on MySQL now I will keep this open until complete.

**Comment by Damdamdu95** [comment]
Okay, I can't wait to see this ^^ .

**Comment by Qballl** [comment]
Just a quick update for you I have it to where the tables are created and 90% of the final save is done what I mean by that is the saving that will happen when the plugin disables. Hopefully, it won't be long until I can bring you guys this update (knock on wood).

**Comment by Damdamdu95** [comment]
Okay ^^. Good luck ^^ !

**Comment by Qballl** [comment]
The MySQL connection and stuff is now almost done I'm working on a data importer now

**Comment by Damdamdu95** [comment]
Okay, good job and good luck for the continuation :3.

**Comment by Qballl** [comment]
Closing this as MySQL is now in Staff+ latest update on spigot
