### ISSUE TITLE
Random Teleport Conflict

### ISSUE THREAD

**Issue by johnsoncui02** [Qballl/StaffPlus#33]
Hello, as a survival server we use random teleport plugins to give players a chance to explore places faster with the command /rtp

but with staff+ the command was overridden by staff+

shown this
![image](https://user-images.githubusercontent.com/23487437/41463866-e048dbae-704c-11e8-927e-b16d34a22d6e.png)

**Comment by Qballl** [comment]
Command uas been removed on my end. Fir a temp fix add this `tp: 'mycommand'` to the commands module of the config if it is not there. If it is there you can just change the stuff on the other side of the : to anything you want

**Comment by johnsoncui02** [comment]
![image](https://user-images.githubusercontent.com/23487437/41478003-f9b96a1c-707a-11e8-827b-bd778b74b985.png)

is that where you wanted me to add that to?

**Comment by Qballl** [comment]
No look for the header that says commands

**Comment by johnsoncui02** [comment]
![image](https://user-images.githubusercontent.com/23487437/41479049-ba1cb23e-707e-11e8-8ec3-c4213db012af.png)
ah, this has to be it right.

**Comment by Qballl** [comment]
Yes make sure that at the bottom of that list of things that the command tp isn't already there

**Comment by Qballl** [comment]
Alright your factions world is all messed up that may be the problem try to copy the format of world if I weren't on my phone I would do it for you

**Comment by johnsoncui02** [comment]
my faction world? I don't have a factions server.

**Comment by Qballl** [comment]
Oh my bad I was flipping between this issue and one on my main plugin

**Comment by Qballl** [comment]
Alright Im gonna to close this issue as one the feature is gone in the update Im working on and I have mentioned how to patch it for now
