### ISSUE TITLE
Just a question - Is there a way to clear a player's inventory?

### ISSUE THREAD

**Issue by FTOtter** [Qballl/StaffPlus#35]
I saw the /strip command to remove armor, but is there a command to clear a player's entire inventory? 

Thanks!

**Comment by Qballl** [comment]
You know I dont think that there is but that wouldn't be hard to add if you want I can work that into this update

**Comment by FTOtter** [comment]
If it all possible, I would love to see that eventually!

**Comment by Qballl** [comment]
I will add it sometime soon but essentials I believe has a command to do this also

**Comment by Qballl** [comment]
Added it in the update Im working on
