### ISSUE TITLE
Error using compass.

### ISSUE THREAD

**Issue by EvilSlime** [Qballl/StaffPlus#36]
https://pastebin.com/nGJfihaT

**Comment by Qballl** [comment]
Well not sure what caused that but I'll try to find out

**Comment by Azoraqua** [comment]
@EvilSlime By accident using PaperSpigot? If so, you can disable the check in the configuration of PaperSpigot (Look for `warnForExcessiveVelocity`).

For the time being, there's not much to fix that issue because it's server-side specifically.

**Comment by Qballl** [comment]
Alright thanks did know that
