### ISSUE TITLE
Plugin not working at all.

### ISSUE THREAD

**Issue by ThelastFPS** [Qballl/StaffPlus#4]
Hello! I'm working on a minecraft factions server and this plugin doesnt seem to work. It only spits out errors. Its 1.8 SPIGOT

**Comment by Qballl** [comment]
Well without the errors I can provide little assistance

**Comment by ThelastFPS** [comment]
Okay. I can see if i can find any errors.

**Comment by ThelastFPS** [comment]
does any of this help?

https://hastebin.com/raw/valeqobesu

The server doesnt save any logs in the logs folder so this is like the only thing I can provide

**Comment by ThelastFPS** [comment]
I also forgot to mention some other plugins also have the issue. They dont show in /plugins and none of the commands for the plugins wont work. I'm using a russian host ;-;

**Comment by Qballl** [comment]
That all has to do with a different plugin. If you want I can test this for you but I will need to know all plugins and their versions

**Comment by ThelastFPS** [comment]
Okay.

**Comment by ThelastFPS** [comment]
https://drive.google.com/open?id=1hBw4oRD_rNp02k367eJ3X_O81etyMD18

**Comment by Qballl** [comment]
I can get it to load and work fine though I found other problems. Rename all your plugins that are named <name> (#) to just <name> bukkit cannot load those named with space and number.

**Comment by ThelastFPS** [comment]
Okay.

**Comment by ThelastFPS** [comment]
Why cant I get it to load tho. ;-;

**Comment by ThelastFPS** [comment]
I've removed all the (#) and stuff.

**Comment by ThelastFPS** [comment]
Going to try again

**Comment by ThelastFPS** [comment]
Still not working..

**Comment by ThelastFPS** [comment]
Well I guess I need to close it since you cant do anything about this.
