### ISSUE TITLE
Prefix space, GUI Hub, reload

### ISSUE THREAD

**Issue by jensuenk** [Qballl/StaffPlus#41]
Hey

I have some issues:

1. When you leave the prefix empty _(general-prefix: "")_ you get a space in front of every chat message.
![screen shot 2018-08-16 at 22 14 23](https://user-images.githubusercontent.com/20428190/44233617-a7662d80-a1a4-11e8-8207-4d78b5f274e2.png)

2. The GUI Hub feature has no title option in the config. The gui title is the same as the item name.
![screen shot 2018-08-16 at 22 15 01](https://user-images.githubusercontent.com/20428190/44233702-e5fbe800-a1a4-11e8-8d8e-97c606cef418.png)

3. "/staffplus reload" does not reload the config + lang files.

4. Players get banned for "Logged out while frozen by an admin" when they type the "/login" password wrong

I'm using spigot 1.12.2 with the latest Staff+ version.

**Comment by Qballl** [comment]
I'm so sorry it has taken so long to get this fixed I will try to get it done with the next update.

**Comment by Qballl** [comment]
Update: Number 2 can already be changed but it is its own config value

**Comment by Qballl** [comment]
Update 3: only thing left to fix is number 3
