### ISSUE TITLE
Error 1.8.8

### ISSUE THREAD

**Issue by Damdamdu95** [Qballl/StaffPlus#44]
https://pastebin.com/zuNmWcE6
I see it's a bug with Citizens or something, at first I thought it was from my modified Spigot but no, so I put Spigot 1.8.8 official, but always the same error. Besides, it disconnects us with a nice error message: https://image.noelshack.com/fichiers/2018/38/5/1537550588-capture.png

**Comment by Damdamdu95** [comment]
EDIT: Okay, sorry, I think it's from a plugin that corrupts StaffPlus, I'll check it out. You can close if you want.

**Comment by Qballl** [comment]
Alright I will look into it

**Comment by Damdamdu95** [comment]
Sorry, it's the collision with your plugin and Reflex (Anticheat), I solved it.
