### ISSUE TITLE
Error in console + crash ! 

### ISSUE THREAD

**Issue by jCripton** [Qballl/StaffPlus#5]
My server version is 1.7.10 PaperSpigot and in console there are these errors and after server crashes.
https://pastebin.com/2HtsgXSE
And when i write /staff in the console saw ''Unknown command'' two times
I have packetlistenerapi and latest versions of Staff+
Sorry for my bad english

**Comment by jCripton** [comment]
[20:37:20 INFO]: Criptos issued server command: /staff
[20:37:20 INFO]: Unknown command.
[20:37:20 INFO]: Unknown command.

**Comment by jCripton** [comment]
Another error nwhen enabling PacketListerApi -> https://pastebin.com/JtH0K8hy

**Comment by Qballl** [comment]
I will look into this but I dont offically support 1.7.10 as it is 4+ years old

**Comment by jCripton** [comment]
So why write that staffplus also works for 1.7, you are inconsistent

**Comment by Qballl** [comment]
Because it should as the old version by shortninja did and I've not removed the code for 1.7

**Comment by Qballl** [comment]
I think I found the problem. What version of the plugin are you running?

**Comment by jCripton** [comment]
Latest version.

**Comment by Qballl** [comment]
Please pastebin your full log

**Comment by jCripton** [comment]
There aren't. Only these logs

**Comment by Qballl** [comment]
I meant the latest .log log

**Comment by jCripton** [comment]
http://www.mediafire.com/file/mz1e4fkuh83k1ic/2017-12-14-2.log ''Log''

**Comment by Qballl** [comment]
Known issue your server is cracked and the plugin does not like that

**Comment by jCripton** [comment]
I use 1.7.10 because pvp is good in this version.

**Comment by jCripton** [comment]
If you don't support 1.7.10 remove this

**Comment by jCripton** [comment]
Can you fix please?

**Comment by Qballl** [comment]
Im posting an update on spigot please reconfirm this issue.

**Comment by Qballl** [comment]
Can you confirm that this is still happening?

**Comment by Qballl** [comment]
Closing as this seems to be fixed if not please respond
