### ISSUE TITLE
owner doenst want to close my issue

### ISSUE THREAD

**Issue by justinbea** [Qballl/StaffPlus#50]
I was trying to use the enable/disable-commands to make fake join and leave message but everycommand i try isnt working and saying 

`12.12 14:49:36 [Server] INFO Unknown command. Type "/help" for help.
12.12 14:49:36 [Server] INFO Unknown command. Type "/help" for help.`

my code is

`  enable-commands: tellraw @a ["",{"text":"+","bold":true,"color":"green"},{"text":"%player%","bold":true,"color":"yellow"}]
  disable-commands: tellraw @a ["",{"text":"+","bold":true,"color":"green"},{"text":"%player%","bold":true,"color":"yellow"}]`

**Comment by justinbea** [comment]
and ive the issue that when you leave the staff mode the items will stay in the inventory

**Comment by Qballl** [comment]
Hmm weird for the first thing in the second one make sure you are up to date on the plugin I already fixed that bug

**Comment by justinbea** [comment]
the plugin is up to date, and also when i disable staff mode the items stay in the inventory, i dont know this is becouse im am using it on 1.12.2?

**Comment by Qballl** [comment]
What version of staffplus are you using because I updated it with clearing

**Comment by justinbea** [comment]
thread closed

**Comment by Qballl** [comment]
Why are you saying thread closed?
