### ISSUE TITLE
Staff+ Feature Request - Ender Chest Viewing 

### ISSUE THREAD

**Issue by RainbowTea** [Qballl/StaffPlus#52]
I love the inventory viewing feature, is it possible to add ender chest viewing in the future? 
Thank you for continuing the plugin.

**Comment by RainbowTea** [comment]
Seeing another players ender chest  for administrative purposes.  Like lets say theyre hiding stolen things in their ender chest.

**Comment by Qballl** [comment]
I can get it done but the player will have to be online

**Comment by RainbowTea** [comment]
Hi sorry for the late reply, thats  fine aswell, just the ability to view it some how without using NBT explorer would be  great. Thank you.

**Comment by ziyaakay** [comment]
You should close this issue tho
