### ISSUE TITLE
Can't open double chests in 1.13.2

### ISSUE THREAD

**Issue by PenguinOwl** [Qballl/StaffPlus#53]
Applies in staff mode.

**Comment by Qballl** [comment]
Any error??

**Comment by PenguinOwl** [comment]
[Here](https://hastebin.com/aposohosiy.apache)

**Comment by Qballl** [comment]
Fixed it on my end closing

**Comment by PenguinOwl** [comment]
Any idea on when the new update is going to be released?

**Comment by Qballl** [comment]
Not yet I have a couple other things to fix/implement
