### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Twister1one** [Qballl/StaffPlus#54]
I have a suggestion, when a note on a player (/notes) add the possibility to make a /notes delete <player> <line> to overdraw a single note.
Also something else, if it is possible to automatically put the date and time of the note and also the author of the note at the beginning of the sentence by default?
Thank you for your plugin, it is great!

**Comment by Qballl** [comment]
Yes that should all be possible and I will try to get it work it out

**Comment by Jeremy3wa** [comment]
Ok, nice, and i have other question, is possible to add permission for /notes ?
or, he exist already ?

**Comment by Qballl** [comment]
If there isn't one already it wouldn't be hard to add

**Comment by Qballl** [comment]
It uses the examine permission
