### ISSUE TITLE
Alerts

### ISSUE THREAD

**Issue by lunarassassin** [Qballl/StaffPlus#55]
I am the owner of a minecraft server. I am OP on the server and have the permission staff.* (Currently using PermissionsEX) My Moderators and Admins will see alerts about when users mine diamonds and etc. My problem is that I do not. I have never disabled them and in the config it shows: alerts-module:
  name-notify: true
  mention-notify: true
  sound: ORB_PICKUP
  xray-alerts:
    enabled: true
    blocks: SPAWNER, DIAMOND_ORE
If you could help that would be great. I am using the 1.13 version of the plugin on a 1.13 server.

**Comment by Qballl** [comment]
You have to have the xray permission

**Comment by lunarassassin** [comment]
I added the xray permission and I still don't get notifications. I also have staff.* as I said before and I am OP.

**Comment by lunarassassin** [comment]
Any help?

**Comment by Qballl** [comment]
I will look into this

**Comment by PenguinOwl** [comment]
Can you post your `permissions.yml`? A good place to upload is [hastebin](https://hastebin.com)

**Comment by lunarassassin** [comment]
I'll post them below, but I often don't add permissions to the my current rank (owner) because I am an OP on the server. I have added the xray permssion though. 
groups:
  default:
    options:
      default: true
      prefix: '&7[Default]&f '
    permissions:
    - modifyworld.*
    - essentials.afk
    - essentials.sethome
    - essentials.home
    - essentials.mail
    - essentials.mail.send
    - essentials.msg
    - essentials.pay
    - essentials.balance
    - essentials.sell
    - essentials.worth
    - essentials.signs.create.buy
    - essentials.signs.create.sell
    - essentials.signs.create.free
    - essentials.help
    - essentials.warp
    - essentials.warp.list
    - essentials.signs.use.kit
    - essentials.signs.use.warp
    - griefprevention.claims
    - essentials.signs.use.sell
    - essentials.signs.use.buy
    - essentials.signs.use.free
    - essentials.warps.shop
    - essentials.warps.spawn
    - essentials.balance
    - essentials.balancetop
    - essentials.balance.others
    - essentials.pay
    - essentials.worth
    - essentials.mail
    - essentials.mail.send
    - essentials.realname
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpdeny
    - essentials.warp
    - essentials.warp.list
    - essentials.signs.use.time
    - essentials.sell.hand
    - guishop.use
    - guishop.sign.use
    - guishop.sign.place
    - guishop.sell
    - gwarps.use
    - gwarps.create
    - gwarps.delete
    - gwarps.modify.name
    - gwarps.modify.description
    - gwarps.help
    - gwarps.update
  zombie:
    options:
      prefix: '&a[Zombie]&f '
    permissions:
    - modifyworld.*
    - essentials.afk
    - essentials.sethome
    - essentials.home
    - essentials.mail
    - essentials.mail.send
    - essentials.msg
    - essentials.pay
    - essentials.balance
    - essentials.sell
    - essentials.worth
    - essentials.signs.create.buy
    - essentials.signs.create.sell
    - essentials.signs.create.free
    - essentials.help
    - essentials.warp
    - essentials.warp.list
    - essentials.signs.use.kit
    - essentials.signs.use.warp
    - griefprevention.claims
    - essentials.signs.use.sell
    - essentials.signs.use.buy
    - essentials.signs.use.free
    - essentials.warps.shop
    - essentials.warps.spawn
    - essentials.balance
    - essentials.balancetop
    - essentials.balance.others
    - essentials.pay
    - essentials.worth
    - essentials.mail
    - essentials.mail.send
    - essentials.realname
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpdeny
    - essentials.warp
    - essentials.warp.list
    - essentials.warps.donator
    - essentials.workbench
    - essentials.hat
    - essentials.nick
    - essentials.signs.use.time
    - essentials.sell.hand
    - guishop.use
    - guishop.sign.use
    - guishop.sign.place
    - guishop.sell
    -  gwarps.use
    - gwarps.create
    - gwarps.delete
    - gwarps.modify.name
    - gwarps.modify.description
    - gwarps.help
    - gwarps.update
  skeleton:
    options:
      prefix: '&8[Skeleton]&f '
    permissions:
    - modifyworld.*
    - essentials.afk
    - essentials.sethome
    - essentials.home
    - essentials.mail
    - essentials.mail.send
    - essentials.msg
    - essentials.pay
    - essentials.balance
    - essentials.sell
    - essentials.worth
    - essentials.signs.create.buy
    - essentials.signs.create.sell
    - essentials.signs.create.free
    - essentials.help
    - essentials.warp
    - essentials.warp.list
    - essentials.signs.use.kit
    - essentials.signs.use.warp
    - griefprevention.claims
    - essentials.signs.use.sell
    - essentials.signs.use.buy
    - essentials.signs.use.free
    - essentials.warps.shop
    - essentials.warps.spawn
    - essentials.balance
    - essentials.balancetop
    - essentials.balance.others
    - essentials.pay
    - essentials.worth
    - essentials.mail
    - essentials.mail.send
    - essentials.realname
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpdeny
    - essentials.warp
    - essentials.warp.list
    - essentials.warps.donator
    - essentials.workbench
    - essentials.hat
    - essentials.nick
    - essentials.nick.color
    - essentials.signs.use.time
    - essentials.sell.hand
    - guishop.use
    - guishop.sign.use
    - guishop.sign.place
    - guishop.sell
    - gwarps.use
    - gwarps.create
    - gwarps.delete
    - gwarps.modify.name
    - gwarps.modify.description
    - gwarps.help
    - gwarps.update
  spider:
    options:
      prefix: '&6[Spider]&f '
    permissions:
    - modifyworld.*
    - essentials.afk
    - essentials.sethome
    - essentials.home
    - essentials.mail
    - essentials.mail.send
    - essentials.msg
    - essentials.pay
    - essentials.balance
    - essentials.sell
    - essentials.worth
    - essentials.signs.create.buy
    - essentials.signs.create.sell
    - essentials.signs.create.free
    - essentials.help
    - essentials.warp
    - essentials.warp.list
    - essentials.signs.use.kit
    - essentials.signs.use.warp
    - griefprevention.claims
    - essentials.signs.use.sell
    - essentials.signs.use.buy
    - essentials.signs.use.free
    - essentials.warps.shop
    - essentials.warps.spawn
    - essentials.balance
    - essentials.balancetop
    - essentials.balance.others
    - essentials.pay
    - essentials.worth
    - essentials.mail
    - essentials.mail.send
    - essentials.realname
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpdeny
    - essentials.warp
    - essentials.warp.list
    - essentials.warps.donator
    - essentials.workbench
    - essentials.hat
    - essentials.nick
    - essentials.nick.color
    - essentials.nick.format
    - essentials.signs.use.time
    - essentials.sell.hand
    - guishop.use
    - guishop.sign.use
    - guishop.sign.place
    - guishop.sell
    - gwarps.use
    - gwarps.create
    - gwarps.delete
    - gwarps.modify.name
    - gwarps.modify.description
    - gwarps.help
    - gwarps.update
  dragon:
    options:
      prefix: '&5&l[Dragon]&f '
    permissions:
    - modifyworld.*
    - essentials.afk
    - essentials.sethome
    - essentials.home
    - essentials.mail
    - essentials.mail.send
    - essentials.msg
    - essentials.pay
    - essentials.balance
    - essentials.sell
    - essentials.worth
    - essentials.signs.create.buy
    - essentials.signs.create.sell
    - essentials.signs.create.free
    - essentials.help
    - essentials.warp
    - essentials.warp.list
    - essentials.signs.use.kit
    - essentials.signs.use.warp
    - griefprevention.claims
    - essentials.signs.use.sell
    - essentials.signs.use.buy
    - essentials.signs.use.free
    - essentials.warps.shop
    - essentials.warps.spawn
    - essentials.balance
    - essentials.balancetop
    - essentials.balance.others
    - essentials.pay
    - essentials.worth
    - essentials.mail
    - essentials.mail.send
    - essentials.realname
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpdeny
    - essentials.warp
    - essentials.warp.list
    - essentials.warps.donator
    - essentials.workbench
    - essentials.hat
    - essentials.nick
    - essentials.nick.color
    - essentials.nick.format
    - essentials.nick.magic
    - essentials.signs.use.time
    - essentials.sell.hand
    - playerparticles.*
    - guishop.use
    - guishop.sign.use
    - guishop.sign.place
    - guishop.sell
    - essentials.sethome.multiple
    - gwarps.use
    - gwarps.create
    - gwarps.delete
    - gwarps.modify.name
    - gwarps.modify.description
    - gwarps.help
    - gwarps.update
  moderator:
    options:
      prefix: '&9&l[Moderator]&f '
    permissions:
    - essentials.fly
    - essentials.give
    - essentials.time
    - OpenInv.openinv
    - essentials.kick
    - essentials.mute
    - essentials.sethome
    - essentials.home
    - essentials.mail
    - essentials.mail.send
    - essentials.msg
    - essentials.pay
    - essentials.balance
    - essentials.sell
    - essentials.worth
    - essentials.signs.create.buy
    - essentials.signs.create.sell
    - essentials.signs.create.free
    - essentials.help
    - essentials.warp
    - essentials.warp.list
    - essentials.signs.use.kit
    - essentials.signs.use.warp
    - griefprevention.claims
    - essentials.signs.use.sell
    - essentials.signs.use.buy
    - essentials.signs.use.free
    - spawnershop.signs.use
    - spawnershop.signs.create
    - spawnershop.buy.*
    - spawnershop.sell.*
    - essentials.warps.shop
    - essentials.warps.spawn
    - essentials.balance
    - essentials.balancetop
    - essentials.balance.others
    - essentials.pay
    - essentials.worth
    - essentials.mail
    - essentials.mail.send
    - essentials.realname
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpdeny
    - essentials.warp
    - essentials.warp.list
    - essentials.warps.donator
    - essentials.hat
    - essentials.nick
    - essentials.nick.color
    - essentials.nick.format
    - essentials.nick.magic
    - essentials.signs.use.time
    - essentials.sell.hand
    - essentials.tp
    - playerparticles.*
    - staff.alerts.xray
    - guishop.use
    - guishop.sign.use
    - guishop.sign.place
    - guishop.sell
    - essentials.sethome.multiple
    - gwarps.use
    - gwarps.create
    - gwarps.delete
    - gwarps.modify.name
    - gwarps.modify.description
    - gwarps.help
    - gwarps.update
  admin:
    options:
      prefix: '&c&l[ADMIN]&f&l '
    permissions:
    - essentials.fly
    - essentials.gamemode
    - essentials.time
    - essentials.kick
    - essentials.mute
    - OpenInv.openinv
    - essentials.hat
    - essentials.heal
    - essentials.item
    - essentials.god
    - essentials.tempban
    - essentials.sethome
    - essentials.home
    - essentials.mail
    - essentials.mail.send
    - essentials.msg
    - essentials.pay
    - essentials.balance
    - essentials.sell
    - essentials.worth
    - essentials.signs.create.buy
    - essentials.signs.create.sell
    - essentials.signs.create.free
    - essentials.kit.dragon
    - essentials.warp.shops
    - essentials.warp.spawn
    - essentials.help
    - essentials.warp
    - essentials.warp.list
    - essentials.signs.use.kit
    - essentials.warp.parkour
    - essentials.warp.kitwars
    - essentials.signs.use.warp
    - griefprevention.claims
    - essentials.warp.rareshop
    - spawnershop.signs.use
    - spawnershop.signs.create
    - spawnershop.buy.*
    - spawnershop.sell.*
    - essentials.warps.shop
    - essentials.warps.spawn
    - essentials.balance
    - essentials.balancetop
    - essentials.balance.others
    - essentials.pay
    - essentials.worth
    - essentials.mail
    - essentials.mail.send
    - essentials.realname
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpdeny
    - essentials.warp
    - essentials.warp.list
    - essentials.warps.donator
    - essentials.hat
    - essentials.nick
    - essentials.nick.color
    - essentials.nick.format
    - essentials.nick.magic
    - essentials.signs.use.time
    - essentials.sell.hand
    - playerparticles.*
    - guishop.use
    - guishop.sign.use
    - guishop.sign.place
    - guishop.sell
    - staff.*
    - essentials.sethome.multiple
    - gwarps.use
    - gwarps.create
    - gwarps.delete
    - gwarps.modify.name
    - gwarps.modify.description
    - gwarps.help
    - gwarps.update
  owner:
    options:
      prefix: '&7&l[OWNER]&7&l '
    permissions:
    - essentials.*
    - OpenInv.openinv
    - worldedit.*
    - permissions.*
    - essentials.afk.kickexempt
    - essentials.kit.owner
    - plots.*
    - playerparticles.*
    - staff.*
    - staff.report
    - staff.alerts.xray
    - gwarps.use
    - gwarps.create
    - gwarps.delete
    - gwarps.modify.name
    - gwarps.modify.description
    - gwarps.help
    - gwarps.update
schema-version: 1
users:
  a32ad814-9fbb-4528-9cde-ba93e45d1e34:
    group:
    - owner
    options:
      name: lunarassassin_
  dd2a1d8b-e97d-4ccb-91dc-14d5b8182897:
    worlds:
      dragon:
        permissions:
        - group
    options:
      name: Richard407
    group:
    - admin
  ca03e274-259c-470e-ab33-c72121ce8749:
    group:
    - moderator
    options:
      name: JJU888
