### ISSUE TITLE
Staf Chat not working

### ISSUE THREAD

**Issue by shilohtony** [Qballl/StaffPlus#56]
Hello. I just recently got the plugin and when i tested  staff chat it didn't seem to work. i did /sc and then i talked but  nothing happened, members could still see it. so with it toggled i did @test  (which is the handle i have selected) and nothing happened, so i did it  again but with /sc disabled. still didn't work. the only thing that  works is /sc  i can't seem to toggle it (NOTE: i am opped with the  permissions as well and members do not have any type of staff+  permission)
--

**Comment by Qballl** [comment]
I will look into this
