### ISSUE TITLE
Ticket System Idea

### ISSUE THREAD

**Issue by Slyloft** [Qballl/StaffPlus#58]
Can you add a push and unclaim ticket feature? It's good for when a mod claims a ticket and find out that the ticket is beyond their status so the ticket is elevated to admin or to the owner also the ability to add notes to the tickets helps too

**example:**
Joe summits a ticket with not much detail. mod Bobby claims tickets and finds out he doesn't have the perms to do what joe need he then unclaims or elevated the ticket to an admin and put a note on it to better clarify the issue and why they could not do it.  Admin Robin opens it and tries to fix the issue but need an owner approval so they unclaim or elevate and a note of the issue. In the meantime player, Joe is seeing the notes so he doesn't feel like no one is helping. Owner claims finished the ticket and close ticket with the answer

**Comment by adamlaughlin** [comment]
To the OP, until you or Qballl find a solution - you can have the mods to whom the original ticket was assigned file their **own** ticket with a message such as "See #113 - //wea is required for this."

**Comment by Azoraqua** [comment]
What about the idea like `/ticket endorse <ticketId>` to push the ticket to a higher ranked authority?
And where only the assigned person can answer the ticket unless someone else is either higher up in the hierarchy or has the permission staff `plusticket.claim.override`.

Feel free to give your opinion on this. :)
