### ISSUE TITLE
Can not disable login feature

### ISSUE THREAD

**Issue by smellyonionman** [Qballl/StaffPlus#59]
Love many aspects of the plugin, especially its ultra-modular nature.

When I change "login" feature to enabled: false, it stops asking me for a password - but still hampers me with slowness.  The negative jump boost doesn't seem to work anymore (at least that's what I assume it was,) as I can still jump around - just not walk.

It would be nice to part with the login feature in my case.

**Comment by Qballl** [comment]
I am sorry it took so long to get back to you I will definitely look into this.

**Comment by adamlaughlin** [comment]
Oh it's no problem at all my friend, we are lucky to have this.  Thank for showing this old classic some love, its GUI performs better than most modern plugins.

**Comment by Qballl** [comment]
Closing this as the login feature is now actually gone for the time being
