### ISSUE TITLE
StaffPlus doesn't work on 1.8

### ISSUE THREAD

**Issue by TheCamoWaffle** [Qballl/StaffPlus#6]
Hey
My StaffPlus isn't working on 1.8 but its working on 1.12, for commands like /staff it says "an internal error occured while attempting to perform this command"

[https://gist.github.com/TheCamoWaffle/16663b6136dd2b9b20a792af147d4108](url)

**Comment by Qballl** [comment]
Send log that link isn't working

**Comment by TheCamoWaffle** [comment]
my latest.log?

**Comment by TheCamoWaffle** [comment]
https://gist.github.com/TheCamoWaffle/99b707461c81f4470e683e6945a9d0c2

**Comment by Qballl** [comment]
Is it cracked when using 1.12 too?

**Comment by TheCamoWaffle** [comment]
Its not a cracked server

**Comment by Qballl** [comment]
Im posting an update on spigot please reconfirm this issue.

**Comment by Qballl** [comment]
Is this issue still happening?

**Comment by TheCamoWaffle** [comment]
Yeah

**Comment by TheCamoWaffle** [comment]
Oh I just updated its working now

**Comment by TheCamoWaffle** [comment]
Thanks

**Comment by Qballl** [comment]
Glad to hear it is now working
