### ISSUE TITLE
Staff being frozen if they don't type their login details quickly enough?

### ISSUE THREAD

**Issue by semmeess** [Qballl/StaffPlus#61]
Hey, me again!
I'm running spigot 1.8.8, Staffplus 3.2.8.2. The player in question has the following related permissions:
` "staff.block", "staff.staffchat", "staff.chat.clear", "staff.chat.toggle", "staff.chat.slow", "staff.alerts.mention", "staff.alerts.namechange", "staff.member", "staff.ticket" "staff.mode", "staff.report", "staff.freeze.bypass", "staff.member"`

They have made their staff login, and use it accordingly, it functions properly. However, if the staff member waits too long before logging in, they are frozen. This is quite inconvenient, is this intentional? Could a config option be added for it? Thanks!
My config.yml is here;

`

lang: lang_en
blocked-commands: /example1, /example2, /example3
blocked-mode-commands: /ah, /trade, /duel, /1v1, /stake, /auctionhouse, /shop, /auchouse, /pay, /eco, /baltop, /trade, /enderchest, /ec, /enchant, /restock, /vote, /buy, /trade
glass-color: 0
glass-title: '&bChoose GUI glass color'
reports-module:
enabled: true
sound: ORB_PICKUP
cooldown: 300
show-reporter: true
warnings-module:
enabled: false
sound: ORB_PICKUP
maximum: 0
ban-command: ban %player% &4Met three warnings. Appeal @ &7www.shithcf.net&4.
clear: 604800
show-issuer: true
staff-chat-module:
enabled: true
handle: '@'
vanish-module:
enabled: true
tab-list: true
show-away: false
chat-module:
enabled: true
lines: 100
slow: 5
blacklist-module:
enabled: true
hoverable: false
character: '_' merging: true words: slut, nigger, nigga, nibba characters: 卐, 卍 domains: com, net, org periods: (), (dot), dot allowed: bypass, assembly, assassin, compass, assume, assault, asset, assort, [www.defiancecraft.com](http://www.defiancecraft.com), defiancecraft.com, hg.defiancecraft.com, build.defiancecraft.com, play.defiancecraft.com, pvp.defiancecraft.com, http://defiancecraft.com, http://www.defiancecraft.com, https://discord.gg/4NYJkh, discord.gg/4NYJkh, [www.discord.gg/4NYJkh](http://www.discord.gg/4NYJkh), [www.discord.gg](http://www.discord.gg), discord.gg tickets-module: enabled: false global: false keep-open: false alerts-module: name-notify: true mention-notify: true sound: ORB_PICKUP xray-alerts: enabled: false blocks: MOB_SPAWNER, DIAMOND_ORE login: enabled: true kick-message: '&cInvalid staff login password!' staff-mode: block-manipulation: false inventory-interaction: false item-change: false vanish-type: TOTAL invincible: true damage: false hunger-loss: false flight: true creative: false original-location: true enable-on-login: false enable-commands: example1 %player%, example2 %player% disable-commands: example1 %player%, example2 %player% disable-on-world-change: false compass-module: enabled: false slot: 1 velocity: 5 item: COMPASS name: '&4Launcher' lore: '&7Launches you towards the, &7location you are facing.' random-teleport-module: enabled: false slot: 2 item: EYE_OF_ENDER name: '&cRandom Teleport' lore: '&7Teleports you to a random player.' random: false vanish-module: enabled: true slot: 2 item: INK_SACK:10 name: '&6&oToggle Vanish' lore: '' item-off: INK_SACK:8 gui-module: enabled: true slot: 4 item: PAPER name: '&6&oView Reports' lore: '' reports-gui: true reports-title: '&c&oActive &4Reports' miner-gui: false miner-title: '&bUnderground users' xray-level: 16 counter-module: enabled: true slot: 8 item: SKULL_ITEM name: '&a&oStaff Online' lore: '' title: '&9&oOnline &bStaff' show-staff-mode: false freeze-module: enabled: true slot: 5 item: ICE name: '&b&oFreeze Player' lore: '' chat: true damage: false timer: 5 sound: ORB_PICKUP prompt: true prompt-title: '&4&lYOU ARE FROZEN' logout-commands: ban %player% cps-module: enabled: true slot: 6 item: WATCH name: '&3&oClick Tester' lore: '' time: 10 max: 16.0 examine-module: enabled: true slot: 7 item: TRAPPED_CHEST name: '&2&oExamine Player' lore: '' title: '&2&oPlayer &aInfo' info-line: food: 0 ip-address: 0 gamemode: 0 infractions: 5 location: 6 notes: 0 freeze: 8 warn: 0 follow-module: enabled: true slot: 3 item: LEASH name: '&9&oFollow Player' lore: '' use-mount: true custom-modules: StaticCommand: enabled: true type: COMMAND_STATIC slot: 9 item: BARRIER name: '&4&oQuit Staff Mode' lore: '' command: staff DynamicCommand: enabled: false type: COMMAND_DYNAMIC slot: 31 item: QUARTZ name: '&4Ban this kid' lore: '&cyou damn lazy staff' command: ban %clicked% &6for shitposting too much with %clicker% ConsoleCommand: enabled: true type: COMMAND_CONSOLE slot: 1 item: FEATHER name: '&bToggle Fly Mode' lore: '&7Toggles flight' command: fly %clicker% Item: enabled: false type: ITEM slot: 34 item: WOOD_AXE name: '&7WorldEdit Wand' lore: '&8don''t grief shitlord!!' permissions: wild-card: staff._
block: staff.block
report: staff.report
report-bypass: staff.report.bypass
warn: staff.warn
warn-bypass: staff.warn.bypass
staff-chat: staff.staffchat
vanish-total: staff.vanish.total
vanish-list: staff.vanish.list
chat-clear: staff.chat.clear
chat-toggle: staff.chat.toggle
chat-slow: staff.chat.slow
blacklist: staff.blacklist
tickets: staff.tickets
mention: staff.alerts.mention
name-change: staff.alerts.namechange
xray: staff.alerts.xray
mode: staff.mode
compass: staff.compass
random-teleport: staff.random-teleport
gui: staff.gui
counter: staff.counter
freeze: staff.freeze
freeze-bypass: staff.freeze.bypass
cps: staff.cps
examine: staff.examine
examine-modify: staff.examine.modify
follow: staff.follow
lockdown: staff.lockdown
revive: staff.revive
member: staff.member
strip: staff.strip
tp: staff.tp
staffplus: staff.staffplus
ipPerm: staff.staffplus.hideip
invClear: staff.staffplus.clearinv
commands:
staff-mode: staff
freeze: freeze
examine: examine
notes: notes
cps: cps
staff-chat: sc
report: report
warn: warn
vanish: vanish
chat: chat
ticket: ticket
alerts: alerts
follow: follow
revive: revive
staff-list: personnel
login: login
register: register
strip: strip
clearInv: clear
storage:
type: flatfile
mysql:
host: localhost
user: root
database: root
password: mypass
port: 3306
migrated: false
config-version: 6201
auto-save: 3600
clock: 2
disable-packets: false
animation-packets: PacketPlayOutBlockBreakAnimation, PacketPlayOutBlockAction
sound-names: random.chestopen, random.chestclosed
metrics: false

**Comment by Qballl** [comment]
Hey in about two weeks I will be working on this that is when i get a break from school I will try to work on it in the meantime though but no guarantees
