### ISSUE TITLE
Staff Mode When in Spectator

### ISSUE THREAD

**Issue by NicsGames** [Qballl/StaffPlus#67]
/staff is a very helpful command, but it doesn't display in spectator mode. I know this may not be possible, but if it is, I would like to see the ability to do /staff in spectator and have the hot bar appear.

**Comment by Qballl** [comment]
That is not possible with spectator mode. I will look into other possibilities

**Comment by Azoraqua** [comment]
Not possible without client-side modifications. 
Spectators cannot interact with their inventory, blocks or entities except in a 'viewer' perspective. 

The only way to give 'Staff Mode' abilities to someone in spectator mode is by commands or perhaps events (yet unreliable). Thus I vote to close this issue as 'Not Fixable'
