### ISSUE TITLE
Invalid Material Type Error upon Startup

### ISSUE THREAD

**Issue by northerncarrots** [Qballl/StaffPlus#70]
### Link of Stack Trace/Error
[Error](https://hastebin.com/iroqosukad.md)

### Actions to Reproduce (if known)

1. Startup Server

### Version
paper-26

**Comment by Qballl** [comment]
That is a config issue just search for those things and replace with the 1.13+ names

**Comment by northerncarrots** [comment]
nice, realized I had to restart the server instead of just reloading the plugin
