### ISSUE TITLE
Exception on /staff

### ISSUE THREAD

**Issue by northerncarrots** [Qballl/StaffPlus#71]
### Link of Stack Trace/Error
[Error](https://hastebin.com/uwinenumag.md)

### Actions to Reproduce (if known)

1. Use command `/staff`
2. Receive staff items and vanish
3. Receive errors in the console

_Staff items do not work
Staff items may be sorted around_

### Version
paper-26

**Comment by Qballl** [comment]
That is a config issue just search for those things and replace with the 1.13+ names

**Comment by Qballl** [comment]
Alright that is my fault I updated the lang files and cannot get them updated via code yet to fix that one in whichever language file you are using add `enable: "whatever the word is for that language"
disable: "same as before`

**Comment by northerncarrots** [comment]
Added
`enable: 'enable'`
`disable: 'disable'`
to **lang_en.yml**

(If this is not what you meant, sorry)

[Output](https://hastebin.com/qobovezuni.md)

**Comment by Qballl** [comment]
Oh my bad it's enabled and disabled

**Comment by northerncarrots** [comment]
Command no longer gives a huge error.
```
[19:38:13 INFO]: The_Internet issued server command: /staff
[19:38:13 INFO]: Unknown command.
[19:38:13 INFO]: Unknown command.
```
staff items still not functional

**Comment by Qballl** [comment]
Those things are unrelated the unknown command is because by default in the config there are two commands done on /staff so easy fix on user end and the item thing needs to be fixed in code

**Comment by Qballl** [comment]
Fixed it finally
