### ISSUE TITLE
/revive not giving items back

### ISSUE THREAD

**Issue by northerncarrots** [Qballl/StaffPlus#72]
### Link of Stack Trace/Error
[Error](https://hastebin.com/uwinenumag.md)

#### These all end with *Player1* not getting their items back

1. Give *Player1* items
2. `/kill Player1`
3. *Player1* respawns
4. `/revive Player1`    
————————————      
1. Give *Player1* Items
2. `/kill Player1`
3. `/revive Player1`
4. *Player1* respawns
⁣————————————
1. Give *Player1* items
2. *Player2* kills *Player1*
3. `/revive Player` (done both before and after *Player1* respawns)
⁣————————————
1. Give *Player1* items
2. *Player2* kills *Player1* and takes the loot
3. `/revive Player` (done both before and after *Player1* respawns)
⁣
### Version
paper-26

[Semi-Related: `/help revive` gives this output with no color-code](https://i.imgur.com/ovRe4b8.png)

**Comment by Qballl** [comment]
Known issue
