### ISSUE TITLE
Maven dependencies for Craftbukkit v1_9_R1 and v1_12_R1 & Spigot (-API) not existent in repository.

### ISSUE THREAD

**Issue by Azoraqua** [Qballl/StaffPlus#75]
Dear author,

The Maven dependencies for Craftbukkit v1_9_R1 and v1_12_R1 also Spigot (-API) for StaffPlusAPI (1.14) are not existing in the specified repositories.
-- See screenshots for more detailed information about the specified dependencies.

It might be needed to update the pom.xml's to add an additional repository or to make sure those versions are uploaded to the already specified repositories.

Kind regards,
Ronald Bunk.

------------------------------------------------------
<img width="800" height="256" alt="Screenshot 2019-07-07 at 04 31 43" src="https://user-images.githubusercontent.com/32922740/60763228-3192db00-a070-11e9-96df-9dd42575d68c.png">
<img width="800" height="256" alt="Screenshot 2019-07-07 at 04 31 26" src="https://user-images.githubusercontent.com/32922740/60763229-335c9e80-a070-11e9-9643-3c429f72c5e0.png">
<img width="800" height="256" alt="Screenshot 2019-07-07 at 04 31 36" src="https://user-images.githubusercontent.com/32922740/60763230-35266200-a070-11e9-81d2-399006dc8eea.png">

**Comment by Qballl** [comment]
Can you double check if you're able to get to qballsrepo.tk?

**Comment by Azoraqua** [comment]
The domain/webhosting in question does not seem to exist at the moment.

**Comment by Qballl** [comment]
Alright then I need to get my repo back up

**Comment by Azoraqua** [comment]
If you want you can use my Github as Maven repositories: https://github.com/AQ-Minecraft/Craftbukkit
Like this:
```xml
<repository>
    <id>aq-minecraft</id>
    <url>https://raw.github.com/AQ-Minecraft/Craftbukkit/</url>
    
    <snapshots>
        <enabled>true</enabled>
        <updatePolicy>always</updatePolicy>
    </snapshots>
</repository>
```

**Comment by Qballl** [comment]
I may if I can't get my repo back up I'm just running my repo off my raspberry pi I was doing nothing else with

**Comment by Azoraqua** [comment]
That's fine. A regular Maven repository might be more elegant, easier to use. 
Using Github is rather difficult to use, in setup.
