### ISSUE TITLE
no

### ISSUE THREAD

**Issue by Vankka** [Qballl/StaffPlus#81]
do not shade log4j in the jar, https://github.com/Qballl/StaffPlus/blob/master/StaffPlusCore/pom.xml#L180 just don't

**Comment by Vankka** [comment]
@Qballl So you choose to completely ignore that your (fork of a) plugin is breaking other plugins by including out-of-date dependencies that shouldn't be in the jar in the first place by closing issues with 0 comment. Shows how much you don't care about your plugin, I guess we'll just tell our users to look for an alternative because you literally choose to literally not help them by doing this.

**Comment by Qballl** [comment]
No it's fixed locally computer crashed before I could push and it was late so I just said screw it I'm sleeping

**Comment by Qballl** [comment]
https://github.com/Qballl/StaffPlus/pull/84
