### ISSUE TITLE
Disable vanish

### ISSUE THREAD

**Issue by Callum22122** [Qballl/StaffPlus#83]
Hi,

Is there anyway to disable vanish when /staff is used? I have tried via the config but still does not work.

**Comment by Azoraqua** [comment]
Alright, that seems like a suitable suggestion. We will look into it.

**Comment by Azoraqua** [comment]
Hi @Callum22122,

There's already an option for that, it's in the configuration file (config.yml) named as `staff-mode.vanish-mode`.

You can find it at line 266 (https://github.com/Qballl/StaffPlus/blob/master/StaffPlusCore/src/main/resources/config.yml#L266).
