### ISSUE TITLE
 [StaffPlus] Task #53 for StaffPlus v3.2.3 generated an exception

### ISSUE THREAD

**Issue by Velocitapder** [Qballl/StaffPlus#9]
`[10:51:54] [Server thread/WARN]: [StaffPlus] Task #53 for StaffPlus v3.2.3 generated an exceptionjava.lang.NullPointerException: null at net.shortninja.staffplus.player.UserManager.getAll(UserManager.java:22) ~[?:?] at net.shortninja.staffplus.player.attribute.infraction.InfractionCoordinator.getWarnings(InfractionCoordinator.java:55) ~[?:?] at net.shortninja.staffplus.Tasks.checkWarnings(Tasks.java:56) ~[?:?] at net.shortninja.staffplus.Tasks.run(Tasks.java:48) ~[?:?] at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigotmc-1.12.2-R0.1.jar:git-Spigot-549c1fa-0459590] at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigotmc-1.12.2-R0.1.jar:git-Spigot-549c1fa-0459590] at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigotmc-1.12.2-R0.1.jar:git-Spigot-549c1fa-0459590] at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigotmc-1.12.2-R0.1.jar:git-Spigot-549c1fa-0459590] at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigotmc-1.12.2-R0.1.jar:git-Spigot-549c1fa-0459590] at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigotmc-1.12.2-R0.1.jar:git-Spigot-549c1fa-0459590] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]`

**Comment by Qballl** [comment]
Known issue

**Comment by Qballl** [comment]
Im gonna close this as I belive it is fixed if not please feel free to open a new one.
