### ISSUE TITLE
Client Crashing when changing to /staff mode

### ISSUE THREAD

**Issue by DeltaKilo97** [Qballl/StaffPlus#92]
Every time I switch to /staff mode, I get 

> Internal Exception: java.lang.NoSuchMethodError: net.minecraft.server.v1_14_R1.MinecraftKey.B()Ljava/lang/String;

Did I config wrong, or is there a different issue here?

[Screenshot Below]
![Screen Shot 2019-07-24 at 11 21 34 AM](https://user-images.githubusercontent.com/53252621/61811079-4d370900-ae06-11e9-8b3a-2c7f54c5b132.png)

**Comment by Qballl** [comment]
Is this on 1.14.4? If so this is a known issue NMS changed

**Comment by DeltaKilo97** [comment]
Yep, my bad, I didn't realize it was known. Thanks!

**Comment by Qballl** [comment]
Reopening until fixed as reminder

**Comment by pixelflowxyz** [comment]
Hey guys; just wondering, any update on this?

**Comment by Qballl** [comment]
We are working in it currently we are replacing packetlistenerapi as I've fixed this but packetlistenerapi is outdated

**Comment by lancehutchinson** [comment]
Hi. Same thing is happening for me when doing /vanish total. Is this the same bug or am i doing something wrong?

**Comment by hitmanneke** [comment]
This error code still pops up when i want to 'follow' a player. Also it happens sometimes with other actions used in /staff mode. Running on 1.14.4

**Comment by lancehutchinson** [comment]
I am using this plugin for staff chat and SuperVanish until this gets fixed.

**Comment by Qballl** [comment]
Alright if you join tye discord there is a pinned version use that

**Comment by Azoraqua** [comment]
I assume the issue is fixed after a year of inactivity.
